export const $yearList = document.querySelector(".year_list")
export const $monthList = document.querySelector(".month_list")
export const $daysField = document.querySelector(".days_field")
export const $datesField = document.querySelector(".dates_field")
export const $calendarOptionButtons = document.querySelectorAll(".calendar_option_button")
export const $showCalendar = document.querySelector(".show_calendar")
export const $decreaseYear = document.querySelector(".decrease_year")
export const $increaseYear = document.querySelector(".increase_year")