export const $yearList = document.querySelector(".year_list")
export const $monthList = document.querySelector(".month_list")
export const $calendars = document.querySelector(".calendars")
export const $calendarOptionButtons = document.querySelectorAll(".calendar_option_button")
export const $showCalendar = document.querySelector(".show_calendar")
export const $removeCalendar = document.querySelector(".remove_calendar")